Repository openshift-s2i/s2i-wildfly, pull requests merged in 2019-03, with the labels that each got.

#184 Upgrade travis golang to 1.10
  .travis.yml
Labels: approved, lgtm, size/XS

#185 Add WildFly 16.0.0.Final
  10.1/test/test-app/src/main/java/Test2.bak
  11.0/test/test-app/src/main/java/Test2.bak
  12.0/test/test-app/src/main/java/Test2.bak
  13.0/test/test-app/src/main/java/Test2.bak
  14.0/test/test-app/src/main/java/Test2.bak
  15.0/test/test-app/src/main/java/Test2.bak
  16.0/Dockerfile
  16.0/contrib/settings.xml
  16.0/contrib/wfbin/standalone.conf
  16.0/contrib/wfcfg/standalone.xml
  16.0/contrib/wfmodules/com/mysql/jdbc/main/module.xml
  16.0/contrib/wfmodules/com/mysql/jdbc/main/mysql-connector-java-5.1.44-bin.jar
  16.0/contrib/wfmodules/org/postgresql/jdbc/main/module.xml
  16.0/contrib/wfmodules/org/postgresql/jdbc/main/postgresql-9.4.1211.jar
  16.0/s2i/bin/assemble
  16.0/s2i/bin/assemble-runtime
  16.0/s2i/bin/run
  16.0/s2i/bin/save-artifacts
  16.0/s2i/bin/usage
  16.0/test/run
  16.0/test/test-app/README.md
  16.0/test/test-app/pom.xml
  16.0/test/test-app/src/main/java/.gitkeep
  16.0/test/test-app/src/main/java/Test.java
  16.0/test/test-app/src/main/resources/.gitkeep
  16.0/test/test-app/src/main/webapp/images/jbosscorp_logo.png
  16.0/test/test-app/src/main/webapp/index.html
  16.0/test/test-app/src/main/webapp/snoop.jsp
  8.1/test/test-app/src/main/java/Test2.bak
  9.0/test/test-app/src/main/java/Test2.bak
  Makefile
  README.md
  imagestreams/wildfly-centos7.json
Labels: approved, lgtm, ok-to-test, size/XXL

#186 Fix WildFly 16 standalone.xml configuration
  16.0/contrib/wfcfg/standalone.xml
Labels: approved, lgtm, ok-to-test, size/S
